Repository wonsongleejo/monkey, pull requests merged in 2025-05, with the labels that each got.

#252 readme: README 작성
  README.md
  docs/images/banner.png
  docs/images/ddd.png
  docs/images/erd.png
  docs/images/infra.png
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/v1/ProductReservationValidator.java
  store-reservation-service/src/main/resources/application.yml
Labels: documentation

#254 readme: 스타일 수정
  README.md
Labels: documentation

#257 refactor: 슬랙 domain 폴더 안에 slack 폴더 제거
  slack-service/src/main/java/com/monkey/slackservice/application/service/SlackServiceImpl.java
  slack-service/src/main/java/com/monkey/slackservice/domain/entity/SlackEntity.java
  slack-service/src/main/java/com/monkey/slackservice/domain/repository/SlackRepository.java
  slack-service/src/main/java/com/monkey/slackservice/domain/slack/repository/SlackRepository.java
  slack-service/src/main/java/com/monkey/slackservice/domain/vo/SlackMessageType.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/persistence/slack/SlackJpaRepository.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/persistence/slack/SlackRepositoryImpl.java
Labels: refactor

#260 Feat: 상품 예약 취소에 kafka 적용
  gateway/src/main/resources/application.yml
  product-reservation-service/build.gradle
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/event/ProductReservationEventProduceV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/event/dto/ProductStockIncreasePayloadV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/v3/ProductReservationServiceApiV3.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/entity/ProductReservationEntity.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/repository/ProductReservationRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/KafkaConfig.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/KafkaConsumerConfig.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/KafkaProducerConfig.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/kafka/KafkaEventListenerV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/kafka/KafkaEventPublisherV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/kafka/dto/ProductStockIncreaseFailPayloadV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationJpaRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationRepositoryImpl.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/v3/ProductReservationControllerApiV3.java
  product-reservation-service/src/main/resources/application.yml
  product-service/build.gradle
  product-service/src/main/java/com/monkey/productservice/application/event/ProductEventProduceV1.java
  product-service/src/main/java/com/monkey/productservice/application/event/dto/ProductStockIncreaseFailPayloadV1.java
  product-service/src/main/java/com/monkey/productservice/application/service/v3/ProductServiceApiV3.java
  product-service/src/main/java/com/monkey/productservice/application/service/v3/ProductServiceImplApiV3.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/KafkaConfig.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/KafkaConsumerConfig.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/KafkaProducerConfig.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/kafka/KafkaEventListenerV1.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/kafka/KafkaEventPublisherV1.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/kafka/dto/ProductStockIncreasePayloadV1.java
  product-service/src/main/resources/application.yml
Labels: feat

#261 feat: 스토어 예약 생성 요청 시 Kafka 메세지 발행
  .gitignore
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV4.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/vo/StoreReservationStatus.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/kafka/StoreReservationConsumer.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/kafka/StoreReservationProducer.java
  store-reservation-service/src/main/resources/application.yml
Labels: feat

#264 chore: store-service 배포용 설정 정리 및 테스트 비활성화
  build.gradle
  slack-service/build.gradle
  slack-service/src/main/resources/application.yml
  store-reservation-service/build.gradle
  store-reservation-service/src/main/resources/application.yml
  store-service/build.gradle
  store-service/src/main/resources/application.yml
Labels: chore

#267 chore: eureka, gateway, user서비스 gradle 수정
  eureka/build.gradle
  gateway/build.gradle
  user-service/build.gradle
Labels: chore

#268 chore: 상품/상품예약 설정 추가
  product-reservation-service/build.gradle
  product-reservation-service/src/main/resources/application.yml
  product-service/build.gradle
  product-service/src/main/resources/application.yml
Labels: chore

#269 feat: 상품 예약에 Kafka 적용
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/v3/ProductReservationServiceApiV3.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/entity/ProductReservationEntity.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/vo/ProductReservationStatus.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/kafka/ProductReservationProducer.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/kafka/ProductStockDecreaseResultConsumer.java
  product-reservation-service/src/main/resources/application.yml
  product-reservation-service/src/test/resources/application-test.yml
  product-service/src/main/java/com/monkey/productservice/application/event/dto/ProductStockDecreaseResultPayloadV1.java
  product-service/src/main/java/com/monkey/productservice/application/service/v4/ProductServiceApiV4.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/KafkaConsumerConfig.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/KafkaProducerConfig.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/kafka/ProductReservationConsumer.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/v1/ProductControllerApiV1.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/v2/ProductControllerApiV2.java
  product-service/src/main/resources/application.yml
  product-service/src/test/resources/application-test.yml
Labels: feat

#272 chore: Host, 일부 Port 환경 변수 처리
  build.gradle
  eureka/Dockerfile
  gateway/src/main/resources/application.yml
  product-reservation-service/src/main/resources/application.yml
  product-service/Dockerfile
  product-service/build.gradle
  product-service/src/main/resources/application.yml
  slack-service/src/main/resources/application.yml
  store-reservation-service/src/main/resources/application.yml
  store-service/src/main/resources/application.yml
  user-service/build.gradle
  user-service/src/main/resources/application.yml
Labels: chore

#276 refactor: 팝업스토어 예약 및 슬랙 도메인 Entity 생성 방식 리팩토링
  slack-service/Dockerfile
  slack-service/build.gradle
  slack-service/src/main/java/com/monkey/slackservice/domain/entity/SlackEntity.java
  slack-service/src/main/resources/application.yml
  store-reservation-service/Dockerfile
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/context/UserContext.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/context/UserContextFilter.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV2.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV3.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV4.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/entity/StoreReservationEntity.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/client/StoreClient.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/StoreReservationJpaRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/StoreReservationRepositoryImpl.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
  store-reservation-service/src/main/resources/application-dev.yml
  store-reservation-service/src/main/resources/application-prod.yml
  store-reservation-service/src/main/resources/application.yml
  store-reservation-service/src/test/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1Test.java
Labels: refactor
