Repository wonsongleejo/monkey, pull requests merged in 2025-04, with the labels that each got.

#2 docs : github template 작성 (#1)
  .github/ISSUE_TEMPLATE/COMMON_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/FEAT_ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 feat : eureka service 구현 (#3)
  server/.gitattributes
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/monkey/server/ServerApplication.java
  server/src/main/resources/application.yml
  server/src/test/java/com/monkey/server/ServerApplicationTests.java
Labels: feat

#12 refactor: issue Templates 수정
  .github/ISSUE_TEMPLATE/COMMON_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/FEAT_ISSUE_TEMPLATE.md
Labels: refactor

#15 feat: ResDTO 클래스
  common-module/src/main/java/com/monkey/commonmodule/dto/ResDTO.java
Labels: feat

#16 feat: common-module 공통 응답/예외처리
  common-module/build.gradle
  common-module/src/main/java/com/monkey/commonmodule/dto/ResDTO.java
  common-module/src/main/java/com/monkey/commonmodule/dto/ResponseCode.java
  common-module/src/main/java/com/monkey/commonmodule/exception/CustomException.java
  common-module/src/main/java/com/monkey/commonmodule/exception/handler/CommonExceptionHandler.java
Labels: feat

#18 feat: BaseEntity 클래스 작성
  common-module/build.gradle
  common-module/src/main/java/com/monkey/commonmodule/entity/BaseEntity.java
Labels: feat

#19 feat: 팝업스토어 예약 생성하는 DTO와 Controller 구현
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/request/ReqStoreReservationPostDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/entity/StoreReservationStatus.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
Labels: feat

#21 feat: 팝업스토어 예약 취소 DTO, Controller 구현
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationCancelDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
Labels: feat

#20 feat: 상품 생성 DTO, Controller 구현
  product-service/build.gradle
  product-service/src/main/java/com/monkey/productservice/application/dto/request/ReqProductPostDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductPostDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/monkey/productservice/domain/entity/ProductEntity.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
Labels: feat

#23 feat: 회원가입, 로그인 DTO와 Controller 구현
  user-service/http/Auth.http
  user-service/src/main/java/com/monkey/userservice/application/dto/request/ReqAuthPostSignInDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/request/ReqAuthPostSingUpDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResAuthPostSignInDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResAuthPostSignUpDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/domain/entity/UserEntity.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/AuthControllerApiV1.java
Labels: feat

#26 feat: 회원 전체 조회, 상제 조회 DTO, Contorller 구현
  user-service/http/User.http
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResUserGetByIdDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResUserGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
Labels: feat

#27 feat: 팝업스토어 생성 DTO, Controller, Entity
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStorePostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/domain/article/entity/StoreEntity.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
Labels: feat

#38 feat: 회원 탈퇴 DTO, Controller 구현
  user-service/http/User.http
  user-service/src/main/java/com/monkey/userservice/domain/entity/UserEntity.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
Labels: feat

#39 feat: 상품 전체조회, 단건조회 dto, controller 작성
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductGetDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
Labels: feat

#41 feat: 팝업스토어 조회, 전체조회 Dto, Controller
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreGetDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
Labels: feat

#43 refactor: 상품 생성/조회 시 Dto, Controller 리팩토링
  product-service/src/main/java/com/monkey/productservice/application/dto/request/ReqProductPostDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/dto/request/ReqProductPutDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/domain/entity/ProductEntity.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
Labels: refactor

#53 feat: Slack 생성 구현
  slack-service/build.gradle
  slack-service/src/main/java/com/monkey/slackservice/application/dto/request/ReqSlackStoreReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/dto/response/ResSlackStoreReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/presentation/controller/SlackControllerApiV1.java
  slack-service/src/main/resources/application.yml
  slack-service/src/test/resources/test/SlackTest.http
Labels: feat

#52 feat: 회원 본인의 한정상품 예약내역 조회 DTO, Controller 구현
  user-service/http/User.http
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResProductReservationClientGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResProductReservationGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
Labels: feat

#64 feat: Slack 생성 기능 구현
  slack-service/build.gradle
  slack-service/src/main/java/com/monkey/slackservice/application/dto/request/ReqSlackStoreReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/dto/response/ResSlackStoreReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/presentation/controller/SlackControllerApiV1.java
  slack-service/src/main/resources/application.yml
  slack-service/src/test/resources/test/SlackTest.http
Labels: feat

#60 refactor: 팝업스토어 등록 수정
  store-service/build.gradle
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStorePostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePutDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/domain/article/entity/StoreEntity.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
Labels: refactor

#62 refactor: 팝업스토어 등록,조회 Dto,Controller 수정
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStorePutDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreGetDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePutDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/domain/article/entity/StoreEntity.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
Labels: refactor

#66 feat: 상품 예약 취소 Dto, Controller
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/request/ReqProductReservationPostDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationPostByIdCancelDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/entity/ProductReservationEntity.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/enums/ProductReservationStatus.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
Labels: feat

#67 feat: 팝업스토어시간대 Controller,Entity,Dto 생성
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotPostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/domain/article/entity/StoreTimeSlotEntity.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreTimeSlotController.java
Labels: feat

#69 feat: 팝업스토어시간대 조회 수정 Dto
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPutDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotGetDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotPutDtoApiV1.java
Labels: feat

#70 feat: 상품 예약내역 전체 조회 Dto, Controller
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
Labels: feat

#76 test: 회원 테스트 코드 작성
  build.gradle
  user-service/build.gradle
  user-service/src/main/resources/application-test.yml
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/UserControllerApiV1Test.java
Labels: test

#77 test: 상품 API 테스트 코드 작성
  product-service/build.gradle
  product-service/src/main/java/com/monkey/productservice/application/dto/request/ReqProductPostDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/dto/request/ReqProductPutDTOApiV1.java
  product-service/src/main/resources/application-test.yml
  product-service/src/main/resources/application.yml
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: test

#79 feat: Swagger 설정
  common-module/build.gradle
  eureka/build.gradle
  gateway/build.gradle
  gateway/src/main/java/com/monkey/gateway/infrastructure/config/CorsConfig.java
  gateway/src/main/resources/application.yml
  product-reservation-service/build.gradle
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/CorsConfig.java
  product-service/build.gradle
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/CorsConfig.java
  slack-service/build.gradle
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/config/CorsConfig.java
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/config/CorsConfig.java
  store-service/build.gradle
  store-service/src/main/java/com/monkey/storeservice/domain/article/entity/StoreEntity.java
  store-service/src/main/java/com/monkey/storeservice/domain/article/entity/StoreTimeSlotEntity.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/config/CorsConfig.java
  user-service/build.gradle
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/CorsConfig.java
Labels: bug, documentation, feat

#87 refactor : 각 서브 모듈 gradle에 적용한 Swagger 설정 수정
  build.gradle
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  product-reservation-service/build.gradle
  product-service/build.gradle
  slack-service/build.gradle
  store-reservation-service/build.gradle
  store-service/build.gradle
  user-service/build.gradle
Labels: documentation, refactor

#86 test: 상품 예약 API 테스트 코드 작성
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/request/ReqProductReservationPostDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
Labels: test

#91 refactor : 회원 테스트 코드 수정
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/UserControllerApiV1Test.java
Labels: refactor

#90 test: 팝업스토어 예약 도메인 테스트 코드 구현
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
  store-reservation-service/src/test/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1Test.java
Labels: test, style

#95 feat: 팝업스토어 예약 도메인 Entity 구현
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetByIdDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostByIdCancelDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/entity/StoreReservationEntity.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/vo/StoreReservationStatus.java
  store-reservation-service/src/main/resources/application.yml
Labels: feat

#94 feat: Product Repository 구현
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
  product-service/src/main/java/com/monkey/productservice/domain/repository/ProductRepository.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: feat

#99 feat: 팝업스토어 예약 Repository 구현 및 CORS 설정 제거
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/CorsConfig.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/CorsConfig.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/config/CorsConfig.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/repository/StoreReservationRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/config/CorsConfig.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/storereservation/StoreReservationJpaRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/storereservation/StoreReservationRepositoryImpl.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/config/CorsConfig.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/CorsConfig.java
Labels: del, feat

#101 feat: 상품 예약 Repository 구현
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/request/ReqProductReservationPostDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationPostByIdCancelDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/entity/ProductReservationEntity.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/repository/ProductReservationRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/vo/ProductReservationStatus.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationJpaRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationRepositoryImpl.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
Labels: feat

#102 feat: slack 도메인 entity 구현
  slack-service/src/main/java/com/monkey/slackservice/domain/slack/entity/SlackEntity.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/entity/StoreReservationEntity.java
Labels: feat, style

#106 bugfix: 쿼리메서드, 테스트 에러 해결
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/repository/ProductReservationRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationJpaRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationRepositoryImpl.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-reservation-service/src/main/resources/application.yml
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
  product-service/src/main/java/com/monkey/productservice/domain/repository/ProductRepository.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/persistence/ProductJpaRepository.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/persistence/ProductRepositoryImpl.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/resources/application.yml
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: bugfix

#109 feat: 회원 리스트 Page적용 및 repository 구현
  user-service/build.gradle
  user-service/src/main/java/com/monkey/userservice/application/dto/request/ReqUserPutDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResProductReservationGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResStoreReservationGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResUserGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/domain/entity/RefreshTokenEntity.java
  user-service/src/main/java/com/monkey/userservice/domain/entity/UserEntity.java
  user-service/src/main/java/com/monkey/userservice/domain/repository/RefreshTokenRepository.java
  user-service/src/main/java/com/monkey/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/RefreshTokenJpaRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/RefreshTokenRepositoryImpl.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/UserJpaRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/UserRepositoryImpl.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/AuthControllerApiV1.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/UserControllerApiV1Test.java
Labels: feat

#117 test: 팝업스토어 예약 도메인 더미데이터 코드 추가
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetByIdDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostByIdCancelDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/entity/StoreReservationEntity.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/repository/StoreReservationRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/vo/StoreReservationStatus.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/config/StoreReservationDataLoader.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/storereservation/StoreReservationJpaRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/storereservation/StoreReservationRepositoryImpl.java
  store-reservation-service/src/main/resources/application.yml
Labels: test, style

#118 test: slack 도메인 더미데이터 코드 추가
  slack-service/src/main/java/com/monkey/slackservice/domain/slack/entity/SlackEntity.java
  slack-service/src/main/java/com/monkey/slackservice/domain/slack/repository/SlackRepository.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/config/SlackDataLoader.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/persistence/slack/SlackRepositoryImpl.java
  slack-service/src/main/resources/application.yml
Labels: test, style

#121 test: 회원 더미 데이터 코드 방식 작성
  user-service/src/main/java/com/monkey/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/QueryDslConfig.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/UserDataLoader.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/UserRepositoryImpl.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/monkey/userservice/UserServiceApplicationTests.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/UserControllerApiV1Test.java
Labels: test

#125 feat: 상품 FeignClient, Service 구현
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/monkey/productservice/domain/entity/ProductEntity.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/feignclient/StoreFeignClient.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/feignclient/UserFeignClient.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/feignclient/dto/StoreDTO.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/feignclient/dto/UserDTO.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
Labels: feat, refactor

#135 feat : 팝업스토어 및 시간대 등록 더미데이터 작성
  store-service/src/main/java/com/monkey/storeservice/infrastructure/config/StoreDataLoader.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/config/StoreTimeSlotDataLoader.java
Labels: feat

#133 refactor : 팝업스토어 dto 및 컨트롤러 수정
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStorePostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotGetDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotPostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreTimeSlotController.java
Labels: refactor

#129 feat:팝업스토어 repository 구현
  store-service/src/main/java/com/monkey/storeservice/domain/article/repository/StoreRepository.java
  store-service/src/main/java/com/monkey/storeservice/domain/article/repository/StoreTimeSlotRepository.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreJpaRepository.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreRepositoryImpl.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreTimeSlotJpaRepository.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreTimeSlotRepositoryImpl.java
Labels: feat

#127 test: 팝업스토어 및 시간대 테스트 코드
  store-service/src/test/java/com/monkey/storeservice/presentaion/controller/StoreControllerApiV1Test.java
  store-service/src/test/java/com/monkey/storeservice/presentaion/controller/StoreTimeSlotControllerApiV1Test.java
Labels: test

#131 style : 팝업스토어 시간대 Entity 변수 수정
  store-service/src/main/java/com/monkey/storeservice/domain/article/entity/StoreTimeSlotEntity.java
Labels: style

#140 feat: 팝업스토어 예약 도메인 Service 구현
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetByIdDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostByIdCancelDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/repository/StoreReservationRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/storereservation/StoreReservationRepositoryImpl.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
Labels: feat, refactor

#141 test: 팝업스토어 예약 테스트에 실제 데이터 저장 로직 추가 및 RestDocs 문서화 보완
  store-reservation-service/src/test/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1Test.java
Labels: test

#143 docs: PR 템플릿 작업 유형에 테스트코드 추가, 수정 설정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#144 fix: 상품 테스트 코드 수정, 공통모듈 의존성 설정 변경
  product-reservation-service/build.gradle
  product-service/build.gradle
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/ProductDataLoader.java
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
  settings.gradle
  slack-service/build.gradle
  store-reservation-service/build.gradle
  store-service/build.gradle
  user-service/build.gradle
Labels: test, bugfix

#147 feat: 팝업스토어 예약 도메인 Feign Client 연결 및 테스트 코드 작성
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/client/StoreClient.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/dto/response/ResStoreTimeSlotDTOApiV1.java
  store-reservation-service/src/main/resources/application.yml
  store-reservation-service/src/test/java/com/monkey/storereservationservice/infrastructure/client/StoreClientTest.java
Labels: feat, test

#148 refactor: 상품 예약 등록 리팩토링
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/request/ReqProductReservationPostDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationPostDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/ProductReservationServiceApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/repository/ProductReservationRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/ProductReservationDataLoader.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/StoreReservationFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResProductClientGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResStoreReservationClientGetDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationJpaRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationRepositoryImpl.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
Labels: refactor, test

#153 refactor: 상품 예약 리팩토링 (취소, 단건 조회)
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/ProductReservationServiceApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationReadValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/entity/ProductReservationEntity.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/UserFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
Labels: refactor, test

#154 feat: JWT 기반 인증 구현 및 Security 설정 구성 과 회원 기능 Service 구현
  .gitignore
  gateway/build.gradle
  gateway/src/main/java/com/monkey/gateway/GatewayApplication.java
  gateway/src/main/java/com/monkey/gateway/filter/AuthorizationHeaderFilter.java
  gateway/src/main/resources/application.yml
  user-service/build.gradle
  user-service/src/main/java/com/monkey/userservice/UserServiceApplication.java
  user-service/src/main/java/com/monkey/userservice/application/dto/request/ReqAuthPostRefreshDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/request/ReqAuthPostSingUpDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResAuthPostRefreshDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResRefreshTokenPostDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/service/AuthServiceApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/service/AuthServiceImplApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/service/UserServiceApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/monkey/userservice/domain/entity/RefreshTokenEntity.java
  user-service/src/main/java/com/monkey/userservice/domain/entity/UserEntity.java
  user-service/src/main/java/com/monkey/userservice/domain/repository/RefreshTokenRepository.java
  user-service/src/main/java/com/monkey/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/SecurityConfig.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/UserDataLoader.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/jwt/CustomUserDetails.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/jwt/CustomUserDetailsService.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/jwt/JWTFilter.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/jwt/JWTUtil.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/RefreshTokenJpaRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/RefreshTokenRepositoryImpl.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/UserJpaRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/persistence/UserRepositoryImpl.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/AuthControllerApiV1.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
  user-service/src/main/resources/application-test.yml
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/AuthControllerApiV1Test.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/UserControllerApiV1Test.java
Labels: feat

#156 feat: 팝업스토어 및 시간대 서비스 생성
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreServiceApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreServiceImplApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreTimeSlotServiceApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreTimeSlotServiceImplApiV1.java
Labels: feat

#160 bugfix: gateway gradle 파일 수정
  gateway/build.gradle
Labels: bugfix

#158 refactor: 팝업스토어 dto, controller , 파일구조 수정
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStorePostDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStorePutDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPutDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreGetDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePutDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotGetDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotPostDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotPutDtoApiV1.java
  store-service/src/main/java/com/monkey/storeservice/domain/entity/StoreEntity.java
  store-service/src/main/java/com/monkey/storeservice/domain/entity/StoreTimeSlotEntity.java
  store-service/src/main/java/com/monkey/storeservice/domain/repository/StoreRepository.java
  store-service/src/main/java/com/monkey/storeservice/domain/repository/StoreTimeSlotRepository.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/config/StoreDataLoader.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/config/StoreTimeSlotDataLoader.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreJpaRepository.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreRepositoryImpl.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreTimeSlotJpaRepository.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/persistence/StoreTimeSlotRepositoryImpl.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreTimeSlotController.java
  store-service/src/test/java/com/monkey/storeservice/presentaion/controller/StoreControllerApiV1Test.java
  store-service/src/test/java/com/monkey/storeservice/presentaion/controller/StoreTimeSlotControllerApiV1Test.java
Labels: refactor, style

#165 style: 파일 이름 변경
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPostDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPutDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreGetDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePostDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStorePutDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotGetDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotPostDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreTimeSlotPutDTOApiV1.java
  store-service/src/main/resources/application.yml
  store-service/src/test/resources/application-test.yml
Labels: style

#167 refactor: 폴더 구조 변경 및 경로 추가
  gateway/src/main/resources/application.yml
  store-service/src/main/java/com/monkey/storeservice/domain/article/repository/StoreRepository.java
  store-service/src/main/java/com/monkey/storeservice/domain/article/repository/StoreTimeSlotRepository.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/SecurityConfig.java
Labels: refactor, style

#168 refactor: 팝업스토어 시간대 PUT 수정
  store-service/src/main/java/com/monkey/storeservice/application/dto/request/ReqStoreTimeSlotPutDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreTimeSlotServiceImplApiV1.java
Labels: refactor

#169 bugfix: Jitpack 배포로 인해 공통모듈 import문 수정
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/entity/StoreReservationEntity.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
Labels: bugfix

#172 feat: 존재하는 timeslot인지 확인하는 로직 추가
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
Labels: feat

#173 refactor: postgreSQL 설정 정보 수정
  product-reservation-service/src/main/resources/application.yml
  product-service/src/main/resources/application.yml
  slack-service/src/main/resources/application.yml
  store-reservation-service/src/main/resources/application.yml
  store-service/build.gradle
  store-service/src/main/resources/application.yml
  user-service/src/main/resources/application.yml
Labels: refactor

#174 refactor: 상품/상품 예약 리팩토링
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/ProductReservationServiceApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationReadValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/ProductFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/StoreFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/StoreReservationFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/UserFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResProductClientGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResStoreClientGetByIdDTOApiV1.java
  product-reservation-service/src/main/resources/application.yml
  product-reservation-service/src/test/java/com/monkey/productreservationservice/config/TestFeignClientConfig.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductGetByIdDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/feignclient/StoreFeignClientApiV1.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/feignclient/UserFeignClientApiV1.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/feignclient/dto/response/ResStoreClientGetByIdDTOApiV1.java
  product-service/src/main/resources/application.yml
  product-service/src/test/java/com/monkey/productservice/config/TestFeignClientConfig.java
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: refactor, test

#177 Refactor: 회원 수정 기능 및 유효성, 예외처리 수정
  user-service/src/main/java/com/monkey/userservice/UserServiceApplication.java
  user-service/src/main/java/com/monkey/userservice/application/dto/request/ReqUserPutDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/monkey/userservice/domain/entity/UserEntity.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/AuthControllerApiV1.java
Labels: refactor

#178 feat: 팝업스토어 예약 도메인 예약 상태 변경 구현
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/request/ReqStoreReservationPutByIdStatusDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPutByIdStatusDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
  store-reservation-service/src/test/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1Test.java
Labels: feat, test

#180 bugfix: 회원 탈퇴 수정 및 회원 테스트코드 수정
  user-service/src/main/java/com/monkey/userservice/domain/entity/BaseEntity.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/UserControllerApiV1Test.java
Labels: test, bugfix

#182 bugfix: 상품/상품예약 테스트 실행 에러 해결
  .gitignore
  product-reservation-service/build.gradle
  product-reservation-service/src/main/resources/application.yml
  product-reservation-service/src/test/java/com/monkey/productreservationservice/ProductReservationServiceApplicationTests.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
  product-reservation-service/src/test/resources/application-test.yml
  product-service/build.gradle
  product-service/src/test/java/com/monkey/productservice/ProductServiceApplicationTests.java
  product-service/src/test/java/com/monkey/productservice/config/TestFeignClientConfig.java
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
  product-service/src/test/resources/application-test.yml
Labels: test, bugfix

#191 bugfix: gateway yml 수정(서비스 filter 추가)
  gateway/src/main/resources/application.yml
Labels: bugfix

#187 bugfix: 회원 예약 내역 FeignClient DTO 구조 수정 (임시)
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResProductReservationClientGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResStoreReservationClientGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResStoreReservationGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/client/ProductReservationFeignClientApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/client/StoreReservationFeignClientApiV1.java
Labels: feat, bugfix

#188 refactor: 상품 AOP 기반 X-User-Id 자동 처리 및 JPA Auditor 적용
  product-service/build.gradle
  product-service/src/main/java/com/monkey/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/monkey/productservice/domain/entity/ProductEntity.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/config/AuditingConfig.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: feat, refactor

#194 feat: 팝업스토어 예약 도메인 사용자 정보 연동
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/client/StoreClient.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/dto/response/ResStoreTimeSlotDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/security/UserContext.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/security/UserContextFilter.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
  store-reservation-service/src/test/java/com/monkey/storereservationservice/config/StoreFeignClientMockConfig.java
  store-reservation-service/src/test/java/com/monkey/storereservationservice/infrastructure/client/StoreClientTest.java
  store-reservation-service/src/test/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1Test.java
Labels: feat

#192 refactor : store Service,Dto,Controller,Entity 수정
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreGetDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreServiceApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreServiceImplApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreTimeSlotServiceApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreTimeSlotServiceImplApiV1.java
  store-service/src/main/java/com/monkey/storeservice/domain/entity/StoreEntity.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreTimeSlotController.java
Labels: feat, refactor

#196 bugfix: 인증을 access토큰으로 수정
  gateway/src/main/java/com/monkey/gateway/filter/AuthorizationHeaderFilter.java
  user-service/src/main/java/com/monkey/userservice/application/service/AuthServiceImplApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/jwt/JWTUtil.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/AuthControllerApiV1.java
Labels: bugfix

#197 refactor : 스토어 및 시간대 예외 처리 코드 수정
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreServiceImplApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/StoreTimeSlotServiceImplApiV1.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreController.java
Labels: refactor

#198 refactor: 상품 예약 리팩토링
  product-reservation-service/build.gradle
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/ProductReservationServiceApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationReadValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/entity/ProductReservationEntity.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/AuditingConfig.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/StoreReservationFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/UserFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResStoreReservationClientGetDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResUserClientGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
Labels: refactor, test

#200 refactor: store 도메인의 URL 변경으로 인해 feign client 수정
  slack-service/build.gradle
  slack-service/src/main/resources/application.yml
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/client/StoreClient.java
Labels: refactor, bugfix

#206 refactor: 상품 예약 시 예외처리 리팩토링, feignclient 전용 스토어 예약 목록 조회 API 추가
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/StoreReservationFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResStoreReservationClientGetDTOApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
Labels: feat, refactor

#209 bugfix: swagger 401 문제 해결을 위해 filter 수정
  gateway/src/main/java/com/monkey/gateway/filter/AuthorizationHeaderFilter.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/SecurityConfig.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/jwt/JWTFilter.java
Labels: refactor, bugfix

#210 del: store-reservation과 slack 분리
  slack-service/src/main/java/com/monkey/slackservice/application/service/SlackServiceImpl.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/slack/SlackClient.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/client/SlackFeignClient.java
Labels: del

#212 feat: 상품/상품예약내역 전체조회 페이징 처리
  product-reservation-service/build.gradle
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/ProductReservationServiceApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/repository/ProductReservationRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationJpaRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationRepositoryImpl.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
  product-service/build.gradle
  product-service/src/main/java/com/monkey/productservice/application/dto/response/ResProductGetDTOApiV1.java
  product-service/src/main/java/com/monkey/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/monkey/productservice/domain/repository/ProductRepository.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/persistence/ProductJpaRepository.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/persistence/ProductRepositoryImpl.java
  product-service/src/main/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: feat

#215 feat: 상품 예약 시 Slack 전송 로직 추가
  slack-service/src/main/java/com/monkey/slackservice/application/dto/request/ReqSlackStoreReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/dto/response/ResSlackProductReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/dto/response/ResSlackStoreReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/service/SlackService.java
  slack-service/src/main/java/com/monkey/slackservice/application/service/SlackServiceImpl.java
  slack-service/src/main/java/com/monkey/slackservice/domain/slack/entity/SlackEntity.java
  slack-service/src/main/java/com/monkey/slackservice/domain/slack/vo/SlackMessageType.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/config/SlackDataLoader.java
  slack-service/src/main/java/com/monkey/slackservice/presentation/controller/SlackControllerApiV1.java
  slack-service/src/main/resources/application.yml
Labels: feat

#217 refactor&feat: 상품/상품예약 api 권한 설정, 상품예약내역 개인조회 api 추가
  product-reservation-service/build.gradle
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/ProductReservationServiceApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/ProductReservationReadValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/repository/ProductReservationRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/UserFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationJpaRepository.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/persistence/ProductReservationRepositoryImpl.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
  product-service/src/main/java/com/monkey/productservice/application/service/ProductServiceApiV1.java
  product-service/src/test/java/com/monkey/productservice/presentation/controller/ProductControllerApiV1Test.java
  user-service/build.gradle
Labels: feat, refactor

#219 refactor: 사용자 정보 조회 서비스 로직 개선
  user-service/src/main/java/com/monkey/userservice/application/service/UserServiceApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/service/UserServiceImplApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/SecurityConfig.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
Labels: refactor

#221 refactor: 상품 예약내역 단건조회 응답에 유저의 slackId 추가
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/dto/response/ResProductReservationGetByIdDTOApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/dto/response/ResUserClientGetByIdDTOApiV1.java
  product-reservation-service/src/test/java/com/monkey/productreservationservice/presentation/controller/ProductReservationControllerApiV1Test.java
Labels: refactor

#224 test: 회원 예약내역 FeignClient 및 테스트 코드 수정
  user-service/http/Auth.http
  user-service/http/User.http
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResProductReservationClientGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResProductReservationGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResStoreReservationClientGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/application/dto/response/ResStoreReservationGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/client/ProductReservationFeignClientApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/client/StoreReservationFeignClientApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/client/dto/ResProductReservationClientGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/client/dto/ResStoreReservationClientGetDTOApiV1.java
  user-service/src/main/java/com/monkey/userservice/infrastructure/config/UserDataLoader.java
  user-service/src/main/java/com/monkey/userservice/presentation/controller/UserControllerApiV1.java
  user-service/src/test/java/com/monkey/userservice/domain/user/controller/UserControllerApiV1Test.java
Labels: documentation, refactor, test

#226 refactor: slack 요청 바디 변경
  slack-service/src/main/java/com/monkey/slackservice/application/dto/request/ReqSlackStoreMessageDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/dto/request/ReqSlackStoreReservationPostDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/dto/response/ResSlackMessageDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/application/service/SlackService.java
  slack-service/src/main/java/com/monkey/slackservice/application/service/SlackServiceImpl.java
  slack-service/src/main/java/com/monkey/slackservice/domain/slack/entity/SlackEntity.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/client/StoreReservationClient.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/dto/response/ResStoreReservationGetByIdDTOApiV1.java
  slack-service/src/main/java/com/monkey/slackservice/infrastructure/message/SlackMessageFormatter.java
  slack-service/src/main/java/com/monkey/slackservice/presentation/controller/SlackControllerApiV1.java
  slack-service/src/test/java/com/monkey/slackservice/presentation/controller/SlackControllerApiV1Test.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/client/StoreClient.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
Labels: refactor

#229 feat: 한정 상품 개인 예약내역 조회 기능에 Redis 적용
  gateway/src/main/resources/application.yml
  product-reservation-service/build.gradle
  product-reservation-service/src/main/java/com/monkey/productreservationservice/ProductReservationServiceApplication.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/v2/ProductReservationServiceApiV2.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/CacheConfig.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/v2/ProductReservationControllerApiV2.java
Labels: feat

#231 feat: 팝업스토어 예약 시 인원 계산 구현
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetByIdDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationGetDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPostDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/response/ResStoreReservationPutByIdStatusDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/domain/StoreReservation/repository/StoreReservationRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/storereservation/StoreReservationJpaRepository.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/infrastructure/persistence/storereservation/StoreReservationRepositoryImpl.java
Labels: feat

#238 feat: 팝업스토어 예약 시 분산 락 적용
  store-reservation-service/build.gradle
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/dto/request/ReqStoreReservationPostDTOApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV3.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV4.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/presentation/controller/StoreReservationControllerApiV1.java
  store-reservation-service/src/main/resources/application.yml
Labels: feat

#241 feat: 예약 취소 시 현재 예약 인원 수 변경하는 로직 추가
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV1.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV2.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV3.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV4.java
Labels: feat

#243 Feat: 상품 예약에서 재고 부분 Redis 적용
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/v1/ProductReservationServiceApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/service/v2/ProductReservationServiceApiV2.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/v1/ProductReservationReadValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/v1/ProductReservationValidator.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/application/validator/v2/ProductReservationValidatorV2.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/domain/service/ProductStockServiceV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/config/RedisConfig.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/feignclient/ProductFeignClientApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/infrastructure/redis/ProductStockRedisServiceImplV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/v1/ProductReservationControllerApiV1.java
  product-reservation-service/src/main/java/com/monkey/productreservationservice/presentation/controller/v2/ProductReservationControllerApiV2.java
  product-service/src/main/java/com/monkey/productservice/application/service/v1/ProductServiceApiV1.java
  product-service/src/main/java/com/monkey/productservice/infrastructure/persistence/ProductJpaRepository.java
Labels: feat, refactor, bugfix

#244 feat : 스토어 조회 및 전체조회 Redis 추가
  gateway/src/main/resources/application.yml
  store-service/build.gradle
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreGetByIdDTOApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/dto/response/ResStoreGetDTOApiV2.java
  store-service/src/main/java/com/monkey/storeservice/application/service/v1/StoreServiceApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/v1/StoreServiceImplApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/v1/StoreTimeSlotServiceApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/v1/StoreTimeSlotServiceImplApiV1.java
  store-service/src/main/java/com/monkey/storeservice/application/service/v2/StoreServiceApiV2.java
  store-service/src/main/java/com/monkey/storeservice/application/service/v2/StoreServiceImplApiV2.java
  store-service/src/main/java/com/monkey/storeservice/infrastructure/config/RedisConfig.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreControllerV1.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreControllerV2.java
  store-service/src/main/java/com/monkey/storeservice/presentation/StoreTimeSlotController.java
  store-service/src/test/java/com/monkey/storeservice/presentaion/controller/StoreControllerV1ApiV1Test.java
  store-service/src/test/java/com/monkey/storeservice/presentaion/controller/StoreTimeSlotControllerApiV1Test.java
Labels: feat, refactor

#248 refactor: 팝업스토어 예약 상태 변경 메서드에서 예약 취소 메서드 분리
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV2.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV3.java
  store-reservation-service/src/main/java/com/monkey/storereservationservice/application/service/StoreReservationServiceImplApiV4.java
  store-reservation-service/src/main/resources/application.yml
Labels: refactor
